import os

admin_html = """
    <button class="btn btn-submit" style="padding: 0.5rem 1rem; font-size: 0.8rem; margin-top: 1rem;" id="adminOpenBtn">进入控制台 (Access Terminal)</button>
  </footer>

  <!-- Admin Modal with dynamic Form injection -->
  <div id="adminPanel" class="admin-modal">
    <div class="admin-header">
      <h2 class="text-gold">系统控制台 System Dashboard</h2>
      <button class="btn btn-submit" id="adminCloseBtn" style="padding: 0.5rem 1rem;">退出</button>
    </div>
    <div class="admin-container" id="adminFormFields">
      <!-- Generated by app.js -->
    </div>
    <div class="admin-actions">
      <button class="btn btn-submit" id="adminSaveBtn" style="background:var(--gold); color:var(--bg); border-color:var(--gold);">保存更改 (Commit Changes)</button>
    </div>
  </div>
"""

for filename in os.listdir('.'):
    if filename.endswith('.html'):
        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if already has adminPanel
        if 'id="adminPanel"' in content:
            continue
            
        # Replace the end of footer
        if '</footer>' in content:
            new_content = content.replace('</footer>', admin_html)
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"Updated {filename}")
